### ISSUE TITLE
能不能加一个输入框

### ISSUE THREAD

**Issue by simonliang20** [Chisw/chenzhilong.chat#3]
能不能加一个输入框，让我共情输入：+1 坐等人事，要走一起走

**Comment by zhmuyu** [comment]
你可以提交PR，做一个json存储

**Comment by Chisw** [comment]
> 能不能加一个输入框，让我共情输入：+1 坐等人事，要走一起走

巧了，我也想加这个，已加好

**Comment by Zerek-Cheng** [comment]
@Chisw 丢localStorage里面吧 不然刷新没了~
